language: php
php:
- 8.0
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS `kytedev`;'
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
script: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text
after_script:
- bash <(curl -s https://codecov.io/bash)
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
env:
  global:
  - secure: R9zNrS21bHLNBYnpkLu+0VJnYdjvfTdseeR+kixNUQO0Y1Tmt5Ka3JdnZSamc4yzwdXqIlDP5JLyE+ifo5mft6kz4c6iVXfU3tIQDTGmzmwD4pOdYGDnB4Q3D/FKgGMbyEvdAiDds8qaC2V1g8VoWpAR4ucvUKuT6M1sLjKRwxufy3z8UlaBvFyYKU6TPU46A1VBqYjOvt6s+iP0HoRskiQBHFVmkJhiYYtBf7v7hVy7nSK2lxiJ3To8G4gUYcAT6KuSkBmY0b3RNDk0bt3FeKwsvYyHmfxfYUMCAFK7lqgiTN0ZpU/rO63nJECL/3Dq06OrOjfqb2IwmrfaSJ3QsOto2B1GCiCsdsYgEfZz26sOdn9t7JFhYTsl4X/my1J7crnOPSFgfKmR/e30niE8gJSERzgaoZVGSoA8poN53p1M+8nYBBU4u8fU2ITxyff7S/bcCf8rPCKfVdl+Q1FVU+ppRO00zg2Ywryp0DqCE3nPEmzIz7uZgjHQ/mg/Ix10+lJNBMBWMowjfCY1qX+Jk0R6BoGPNRoZFa/ZBoFOcjeP8uPcoA1ErljWBCdI8BMBFmHJSIppmoObRj9RBUZRYcagv7aEy8uVhqs3dHOG48RtszjjOL2U68PF+qVLrxvSLAljLgZjymVFvag2cnw828vQIU/WgEe7lSdWh7RdO44=
  - secure: Z9eb6LCFgO/M2YQbIN0tgdHzjfA+TYuZ3zDSQyF7i1NRQBYrVyLybMAwtgi81ZOx3uaqZoNEO61ofyI0wCN9WWcp4CcyVKVK1T8gVVfREO7WoIyzX2GXcYuoU0AWrK3ehAPJpOLQv2Ru7OMqGLmGfGdDY5DwjOwQ2j7N8+rYZcP1UNKjzSC+/T7gN6Bln1KMnCqFEN3M+u4BZy9aYBXv/+UvPKnHnkPNfteC5cUaPdktljxoFgSBkwg5b+9NHI+zjrQjDC6zzPkcIxWeSVOhNO4sg/+RxIYPUFCiwP4zNxX0uO8QsY1EIEoe4DnHFUyqw/G/umlx8r0oyVV5Xqv5AadrEZEvpxqan+677AQobsKhVh9wRGZHD1tAahtr74Xfbeniu1eLqPIyvSs1XdnpX+TSQPufsDHp1m/Uqhw4jAA0XuINJPVjY8jwJeoQh+gvJoe8GrlJYx4uvzkswjOieXVwIhWBvhH6Y3Bt7M4+FL+PTUnMZ2YVYpwS6D/lFavmtvW4sxF9dcEDJMJpY+4PEjTb7OSSdSdaPkIgoTnEAVhJLEhlXX9tVzXCOlSoM5VPlMAvZjWrDn0iLJR5E9L96CVR9uR6asZ47CdlsD+fFYKzJaeuBfcFoe8NrRSeYWdwBZHL6kRBMPjx9s1G+r26HzjkaN9d/EBZxdn9f/emEmw=
  # - secure: XSbxEbNQFZZlXJuyRHV9F3ap3yLDnVgisO8owg0Eu8qBXfggYocroqzRglWvXIWqXtVyLgMpYl+qlg3EHKnmQzmN2+dAbLoowyc+HOJgEDiWxI0/yEho6VebaEcwa/XxSxyOYHnBKMhBH+9THp44N3Qr1ODiaE+iH9ih1Qgb/C3rwsBt6l8xu6wyFjA8RPtcXuv1wrTAR3ZheSpd2Jf5v9Gyn4X24HogckrfkwgZnUAKVGwIWayXNIRwlBVRJlNFjT3rYpxIWsVaKsaXgo/bJtnPNBUhwAhhnXHsAaaC5S77UWOV5alx7m0+FUTBUIRNARCkd27sJTZLSXKb64ixn8+UAMQrObC8eemSy6IdkozNarwL3s1kcku5fqDPGQMeL25sNliJ1juFItzu/ixHbUuAVRqVE0o1clEFg3Xe1bHg5SVvAd5A5KXQWmqvsvhnxAvdRG2wZG0o96E/Idc64WazHZcvBOX6RV04bFurY8GyOXhg7maQty2+JLgUVGObotYVUNRHTaVAcdGPuwtQD9xNySnrvPJuvRREf8p48QT8eBKq/kL5GXbW/y+VmnJx6cQm+gXUJP/ZaomtIHc56XctX673MfURruq9mgOhOgEvEJ8nHmSRnIqzFdMqcKnRkB5kdyUUL8oJLPy06BwdH8vt43LnHEAIfUL8c5kgylY=
